version: '3'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/Projects/hr_bot/data/db

  hr_bot:
    restart: always
    build: /Projects/hr_bot
    volumes:
      - /Projects/hr_bot:/Projects/hr_bot
    depends_on:
      - mongo

volumes:
    mongodb_data:
